checkit/urls.py
"""
This file contains all of the urls for the
checkit app. All urls go to the views.py file
"""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

# These patterns are checked in order, and a regular
# expression is applied to each to see if the requested
# url matches the request.
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('checks/', views.check_index, name='check_index'),
    path('checks/<int:check_id>/', views.check_edit, name='check_edit'),
    path('checks/<int:check_id>/delete/', views.check_delete, name='check_delete'),
    path('checks/<int:check_id>/letter1/', views.check_letter1, name='check_letter1'),
    path('checks/<int:check_id>/letter2/', views.check_letter2, name='check_letter2'),
    path('checks/<int:check_id>/letter3/', views.check_letter3, name='check_letter3'),
    path('checks/<int:check_id>/pay/', views.check_pay, name='check_pay'),
    path('accounts/', views.account_index, name='account_index'),
    path('accounts/new/', views.account_new, name='account_new'),
    path('accounts/<int:account_id>/', views.account_edit, name='account_edit'),
    path('accounts/<int:account_id>/delete/', views.account_delete, name='account_delete'),
    path('accounts/<int:account_id>/checks/', views.account_check_index, name='account_check_index'),
    path('accounts/<int:account_id>/checks/new/', views.account_check_new, name='account_check_new'),
    path('companies/', views.company_index, name='company_index'),
    path('companies/new/', views.company_new, name='company_new'),
    path('companies/choose/', views.company_choose, name='company_choose'),
    path('companies/<int:company_id>/', views.company_edit, name='company_edit'),
    path('companies/<int:company_id>/delete', views.company_delete, name='company_delete'),
    path('companies/<int:company_id>/register/', views.register, name='register'),
    path('companies/<int:company_id>/simulate/', views.company_simulate, name='simulate'),
    path('companies/stopsimulate/', views.company_stop_simulate, name='stop_simulate'),
    path('letters/', views.letter, name='letter'),
    path('users/', views.user_index, name='user_index'),
    path('users/<int:user_id>/', views.user_edit, name='user_edit'),
    path('users/<int:user_id>/checks/', views.user_check_index, name='user_check_index'),
    path('users/<int:user_id>/delete/', views.user_delete, name='user_delete'),
    path('profile/', views.profile, name='profile'),
    path('report/', views.report, name='report')
]

unicoders/urls.py
from django.contrib import admin
from django.urls import include, path

# The error handler pages
handler404 = 'checkit.views.handler404'
handler500 = 'checkit.views.handler500'

# The basic paths, including the actual checkit app
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('checkit.urls')),
]

checkit/models.py
"""
This file includes all of the data for how the database stores
its information. It includes the models, relationships, and fields
as Python classes. To generate a database migration when a model
has been changed or added, run

    python manage.py makemigrations

To actually migrate the data into the database, run

    python manage.py migrate

Models also have helpful fields that may be used in templates, or
methods that change data on them.
"""

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import RegexValidator, MaxValueValidator, MinValueValidator
import datetime


class Company(models.Model):
    """
    The company model. It includes all necessary attributes, and it
    is the main/top model for the whole system.
    """
    name = models.CharField(max_length=50, null=True)
    desc = models.CharField(max_length=1000, null=True)
    wait_period = models.IntegerField(default=10)
    street = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=2, null=True)
    zip_code = models.CharField(max_length=5, null=True, validators=[
        RegexValidator(r'^[0-9]{5}$',
                       message='Zip code must be five digits.',
                       code='invalid_zip_code')
    ])
    late_fee = models.DecimalField(decimal_places=2, max_digits=10, default=50, null=True)
    date_created = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        """Returns a textual representation of the company"""
        return self.name

    class Meta:
        indexes = [  # Create indexes on fields that are searched.
            models.Index(fields=['name'], name='company_name_idx'),
            models.Index(fields=['date_created'], name='company_date_created_idx')
        ]
        verbose_name_plural = 'companies'


class Account(models.Model):
    """
    The account model includes a foreign key to a company. It
    also includes all of the data for an account, including number,
    routing number, and address.
    """
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50, null=True)
    number = models.CharField(max_length=32, null=True, validators=[
        RegexValidator(r'^[0-9a-zA-Z]*$',  # Only alphanumeric characters
                       message='Only alphanumeric characters are allowed.',
                       code='invalid_account_number')
    ])
    route = models.CharField(max_length=9, null=True, validators=[
        RegexValidator(r'^[0-9]{9}$',  # 9 digits is a routing number in US
                       message='Routing number must be 9 digits.',
                       code='invalid_routing_number')
    ])
    street = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=2, null=True)
    zip_code = models.CharField(max_length=5, null=True, validators=[
        RegexValidator(r'^[0-9]{5}$',  # Zip code is just 5 digits, not worrying about rest
                       message='Zip code must be five digits.',
                       code='invalid_zip_code')
    ])
    date_created = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        """Return a textual representation of the account - the name"""
        return self.name

    class Meta:
        indexes = [  # Create indexes on fields that are searched.
            models.Index(fields=['date_created'], name='account_date_created_idx'),
            models.Index(fields=['name'], name='account_name_idx'),
            models.Index(fields=['number'], name='account_number_idx'),
            models.Index(fields=['route'], name='account_route_idx'),
            models.Index(fields=['street'], name='account_street_idx')
        ]


class Check(models.Model):
    """
    The check model. It includes a foreign key to the user who created it,
    a foreign key to the account it's associated with, and all other necessary
    fields. The standard fields are check number, amount, and date.
    Other fields:
        paid: Whether or not the check has been paid, manually or actually
        amount_paid: The amount currently paid on the check
        letter1_date: The date that letter 1 was generated
        letter2_date: The date that letter 2 was generated
        letter3_date: The date that letter 3 was generated
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    number = models.IntegerField(default=0, null=True)
    amount = models.DecimalField(decimal_places=2, max_digits=10, null=True)
    paid = models.BooleanField(default=False)
    amount_paid = models.DecimalField(decimal_places=2, max_digits=10, default=0, null=True)
    date = models.DateField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    letter1_date = models.DateField(null=True)
    letter2_date = models.DateField(null=True)
    letter3_date = models.DateField(null=True)
    paid_date = models.DateField(null=True)

    def __str__(self):
        """Returns a textual representation of the check"""
        return '{}: {}'.format(self.account.name, self.amount)

    def current_letter(self):
        """
        Determins which letter should be generated for the check.
        :return:
            0 if already paid
            1 if letter 1
            2 if letter 2
            3 if letter 3
            -1 if no letter needs to be generated
        """
        delta = (datetime.datetime.now().date() - self.date_created.date()).days
        wait_period = self.account.company.wait_period
        if self.paid:
            return 0
        if not self.letter1_date:
            return 1
        elif not self.letter2_date and delta >= wait_period:
            return 2
        elif not self.letter3_date and delta >= wait_period * 2:
            return 3
        return -1

    def current_letter_template(self):
        """
        Gets the current template that needs to be generated for a letter
        :return: The string of the current letter template
        """
        letter = self.current_letter()
        setattr(self, 'letter{}_date'.format(letter), datetime.datetime.now().date())
        self.save()
        return 'letters/letter{}.html'.format(letter)

    def row_status(self):
        """
        How should the check display in a table?
        :return:
            'row-success' if check has been paid
            'row-warning' if letter needs to be generated
        """
        letter = self.current_letter()
        if letter == 0:
            return 'row-success'
        if 1 <= letter <= 3:
            return 'row-warning'

    def amount_due(self):
        """How much is due for this check?"""
        return self.account.company.late_fee + self.amount - self.amount_paid

    def pay(self, amount):
        """
        Pays a certain amount on the check
        :param amount: The amount to pay
        :return: A string for how much or whether the check was fully paid
        """
        ret = 'Successfully paid ${:.2f}'.format(amount)
        self.amount_paid += amount
        if self.amount_paid >= self.account.company.late_fee + self.amount:
            self.paid = True
            self.paid_date = datetime.datetime.now().date()
            ret = 'Successfully paid off check!'
        self.save()
        return ret

    class Meta:
        indexes = [  # Create indexes on fields that are searched.
            models.Index(fields=['date_created'], name='check_date_created_idx')
        ]


class Profile(models.Model):
    """
    The profile model, which contains extra data besides the
    Django defaults for a user.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.PROTECT, null=True)
    is_supervisor = models.BooleanField(default=False)
    records_per_page = models.IntegerField(default=10, validators=[
        MaxValueValidator(100),  # No more than 100 records per page
        MinValueValidator(1)  # No less than 1 record per page
    ])

    def __str__(self):
        """Returns a textual representation of the user, the username"""
        return self.user.username

    def full_name(self):
        """Returns the user's full name, first + last"""
        return '{} {}'.format(self.user.first_name, self.user.last_name)

    def admin(self):
        """Whether or not the user is an administrator"""
        return self.user.is_superuser

    def supervisor(self):
        """Whether or not the user is a supervisor"""
        return self.is_supervisor

    def supervisor_up(self):
        """Whether or not the user is a supervisor or admin"""
        return self.admin() or self.supervisor()

    def simulate(self, company):
        """Makes an administrator start simulating a company"""
        self.company = company
        self.save()

    def stop_simulate(self):
        """Stops an administrator's simulation"""
        self.company = None
        self.save()

    def admin_simulating(self):
        """Whether or not an admin is simulating a company"""
        return self.admin() and self.company is not None

    def admin_not_simulating(self):
        """Whether or not the user is an admin and not simulating"""
        return self.admin() and self.company is None

    def regular(self):
        """
        Whether or not the user is a supervisor or regular user,
        which includes a simulated admin user
        """
        return (not self.admin()) or self.admin_simulating()


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):

checkit/templates/checks/edit.html
{% extends 'base.html' %}

{% block title %} {{block.super}} - Edit Check {% endblock %}

{% block content %}

{% include 'snippets/back_link.html' with back_url='check_index' page_name='All Checks' %}
<div class='row'>
  <div class='col-sm-12 col-md-8 col-lg-6 mx-auto form-box'>
    <h2 class='text-center'>Edit Check</h2>
    <p class='text-center'><i>{{ check.account.name }}</i></p>
    <hr/>

    <form method='post' >
      {% csrf_token %}

      {{ form.non_field_errors }}

      <div class='row'>
        <div class='col-sm-12 {% if not user.profile.supervisor_up %}hidden{% endif %}'>
          <label for='id_paid'>Paid?</label>
          {{ form.paid }}
          {{ form.paid.errors }}
        </div>
        <div class='col-sm-12'>
          {% include 'snippets/field.html' with field=form.number %}
        </div>
        <div class='col-sm-12'>
          {% include 'snippets/field.html' with field=form.amount %}
        </div>
        <div class='col-sm-12'>
          <label for='id_date'>Date:</label>
          {{ form.date }}
          {{ form.date.errors }}
        </div>
        <div class='col-sm-12 col-md-4'>
          <a href='{% url 'check_letter1' check.id %}' class='btn btn-secondary btn-block'>Letter 1</a>
        </div>
        <div class='col-sm-12 col-md-4'>
          <a href='{% url 'check_letter2' check.id %}' class='btn btn-secondary btn-block'>Letter 2</a>
        </div>
        <div class='col-sm-12 col-md-4'>
          <a href='{% url 'check_letter3' check.id %}' class='btn btn-secondary btn-block'>Letter 3</a>
        </div>
        <div class='col-sm-12'>
          <input class='submit btn btn-primary btn-block' type='submit' value='Update Check' id='submit'/>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

checkit/templates/checks/index.html
{% extends 'base.html' %}

{% block title %} {{block.super}} - Checks {% endblock %}

{% block content %}

{% if back_link %}
  {% include 'snippets/back_link.html' with back_url=back_link page_name=back_name index_page='yes' %}
{% endif %}
<div class='row header-content'>
  <div class='col-sm-12'>
    <h3>{{ heading }}</h3>
  </div>
  <div class='col-sm-12 col-md-6'>
    <input value='{% if search %}{{search}}{% endif %}' id='search' type='text' placeholder='Search Account Name' onkeypress='handlesearch(event)'/>
  </div>
  {% if not user.profile.admin %}
    <div class='col-sm-12 col-md-6'>
      <a href='{% url 'letter' %}' class='btn btn-primary float-right no-margin'><i class='fas fa-envelope'></i> Generate Letters</a>
    </div>
  {% endif %}
  <div class='col-sm-12'><hr/></div>
</div>

<div class='row'>
  <div class='col-sm-12'>
    <table class='table data-table'>
      <thead>
        <tr>
          <th scope='col'>{% include 'snippets/sort-link.html' with field='account__name' heading='Account Name' %}</th>
          <th scope='col'>{% include 'snippets/sort-link.html' with field='amount' heading='Amount' %}</th>
          <th scope='col'>{% include 'snippets/sort-link.html' with field='amount_paid' heading='Amount Paid' %}</th>
          <th scope='col'>{% include 'snippets/sort-link.html' with field='date' heading='Check Date' %}</th>
          <th scope='col'>{% include 'snippets/sort-link.html' with field='date_created' heading='Date Created' %}</th>
          <th scope='col'>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for check in checks %}
          <tr onclick='window.location = "{% url 'check_pay' check.id %}"' class='{{ check.row_status }}'>
            <td>{{ check.account.name }}</td>
            <td>{{ check.amount }}</td>
            <td>{{ check.amount_paid }}</td>
            <td>{{ check.date }}</td>
            <td>{{ check.date_created.date }}</td>
            <td>
              <ul class='actions'>
                <li><a href='{% url 'check_edit' check.id %}' data-toggle='tooltip' title='Edit Check'>
                  <i class='fas fa-cog'></i>
                </a></li>
                {% if not check.paid %}
                  <li><a href='{% url 'check_pay' check.id %}' data-toggle='tooltip' title='Pay Check'>
                    <i class='fas fa-shopping-cart'></i>
                  </a></li>
                {% endif %}
                {% if user.profile.admin %}
                  <li><a onclick='return confirm("Are you sure you want to delete check #{{ check.number }}?")' href='{% url 'check_delete' check.id %}' data-toggle='tooltip' title='Delete Check'>
                    <i class='fas fa-trash'></i>
                  </a></li>
                {% endif %}
              </ul>
            </td>
          </tr>
        {% empty %}
          <tr>
            {% if search %}
              <td colspan='6'>Your search "{{search}}" did not match any checks.</td>
            {% else %}
              <td colspan='6'>No checks found.</td>
            {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% include 'snippets/pagination.html' with objects=checks %}
  </div>
</div>

{% endblock %}

checkit/templates/checks/new.html
{% extends 'base.html' %}

{% block title %} {{block.super}} - New Check {% endblock %}

{% block content %}

{% include 'snippets/back_link.html' with back_url='account_index' page_name='All Accounts' %}
<div class='row'>
  <div class='col-sm-12 col-md-8 col-lg-6 mx-auto form-box'>
    <h2 class='text-center'>Add a Check</h2>
    <p class='text-center'><i>{{ account }}</i></p>
    <hr/>

    <form method='post' >
      {% csrf_token %}

      {{ form.non_field_errors }}

      <div class='row'>
        <div class='col-sm-12'>
          {% include 'snippets/field.html' with field=form.number %}
        </div>
        <div class='col-sm-12'>
          {% include 'snippets/field.html' with field=form.amount %}
        </div>
        <div class='col-sm-12'>
          <label for='id_date'>Date:</label>
          {{ form.date }}
          {{ form.date.errors }}
        </div>
        <div class='col-sm-12 col-md-6 order-2'>
          <input class='submit btn btn-primary btn-block' type='submit' value='Create Check'/>
        </div>
        <div class='col-sm-12 col-md-6 order-1'>
          <input class='submit btn btn-secondary btn-block' name='again' type='submit' value='Create and Add Another'/>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

checkit/templates/checks/pay.html
{% extends 'base.html' %}

{% block title %} {{block.super}} - Pay Check {% endblock %}

{% block content %}

{% include 'snippets/back_link.html' with back_url='check_index' page_name='All Checks' %}
<div class='row'>
  <div class='col-sm-12 col-md-8 col-lg-6 mx-auto form-box'>
    <h2 class='text-center'>Pay Check</h2>
    <p class='text-center'><i>{{ check.account.name }}</i></p>
    <hr/>

    <form method='post' >
      {% csrf_token %}

      {{ form.non_field_errors }}

      <div class='row'>
        <div class='col-sm-12'>
          <p class='no-margin bg-danger'>+ Check Amount: ${{ check.amount }}</p>
          <p class='no-margin bg-danger'>+ Late Fee: ${{ check.account.company.late_fee }}</p>
          {% if check.amount_paid %}<p class='no-margin bg-success'>- Already Paid: ${{ check.amount_paid }}</p>{% endif %}
          <hr>
          <p>Total Due: {{ check.amount_due }}</p>
        </div>
        <div class='col-sm-12'>
          {% include 'snippets/field.html' with field=form.amount %}
        </div>
        <div class='col-sm-12'>
          <input class='submit btn btn-primary btn-block' type='submit' value='Pay Check'/>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}